id: IB30E3333
legacy_id: P000448
ocr_import_info:
  bdrc_scan_id: W8LS20768
  source: bdrc
  ocr_info:
    timestamp: '2020-03-22T09:18:29'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-27T13:24:55.249662+00:00'
last_modified: 2022-08-27 21:25:09.134431
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W8LS20768
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW8LS20768
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: མཁས་འཇུག་གི་མཆན་འགྲེལ་ལེགས་བཤད་སྣང་བའི་འོད་ཟེར་རལ་གྲི་དང་ཨུཏྤལའི་སྐོར།
  author: འཇུ་མི་ཕམ་འཇམ་དབྱངས་རྣམ་རྒྱལ་རྒྱ་མཚོ།
statistics:
  ocr_word_mean_confidence_index: 0.8818247167575349
  ocr_word_median_confidence_index: 0.9800000190734863
quality: null
bases:
  I8LS20831:
    source_metadata:
      id: http://purl.bdrc.io/resource/I8LS20831
      total_pages: 516
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I8LS20831.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.8818247167575349
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
